### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.libsdl.app/com.ravbug.sdlmin.SDLActivity}

### ISSUE THREAD

**Issue by 8Observer8** [Ravbug/sdl3-sample#8]
Please, help me to solve this problem. I don't have any ideas:

```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.libsdl.app/com.ravbug.sdlmin.SDLActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ravbug.sdlmin.SDLActivity" on path: DexPathList[[zip file "/data/app/org.libsdl.app-2/base.apk"],nativeLibraryDirectories=[/data/app/org.libsdl.app-2/lib/arm, /data/app/org.libsdl.app-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2625)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ravbug.sdlmin.SDLActivity" on path: DexPathList[[zip file "/data/app/org.libsdl.app-2/base.apk"],nativeLibraryDirectories=[/data/app/org.libsdl.app-2/lib/arm, /data/app/org.libsdl.app-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2615)
... 9 more
```

**Comment by Ravbug** [comment]
Fixed in https://github.com/Ravbug/sdl3-sample/commit/c2a5f88d7baa56029e1100d6e4e26bb9367d7d36. The issue was the `namespace "com.ravbug.sdlmin"` line, which I replaced in that commit.

**Comment by 8Observer8** [comment]
Yes, it works! Thanks a lot!
